# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MNirRa8CMXWcbT6uEms9ba8cHGo9UUH
"""

#!/usr/bin/env python
# -- coding: utf-8 --4

import numpy as np
import math
def is_valid_probability_dist(var):
    x = np.zeros((var))
    p_x = np.zeros((var))
    for i in range(var):
        x[i] = float(input('Enter the value of x : '))
        p_x[i] = float(input('Enter the value of P(x) : '))
        if p_x[i] < 0 or p_x[i] > 1.0 :
           print('Probability of an event should be 0 to 1.')
           return False
    p_sum = math.fsum(p_x)
    print('Summation of P(x) over the given sample space = ', p_sum)
    if p_sum != 1.0  :
        print('The Summation of P(x) over the given sample space is not 1.0.')
        return False
    return True

def driver():
    obv = input('Enter the number of observations : ')
    valid = is_valid_probability_dist(int(obv))
    if valid :
        print('The given distribution exist.')
    else:
        print('The given distribution does not exist.')
    
    
driver()